### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by MarleyRobert** [pytholic/Yolov5Export#4]
Hello @pytholic,

first of all thanks for your repo! I had a lot of trouble converting yolov5 into coreml and your repo helped a lot. I was able to convert a model which was trained by somebody else, but the model isn't performing as good as I which. So I need to train it myself.

So at first I wanted to test if I could easily export a custom trained model with version 6 (I think I read somewhere that u trained you model with version 6), so I tried to convert the model from poetry_yolov5/yolov5_6.0. Unfortunately I did get this error

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5-coreml-tools/src/coreml_export/main.py", line 313, in main
    model = torch.load(opt.model_input_path, map_location=torch.device('cpu'))[
  File "/Users/michelschumacher/Library/Caches/pypoetry/virtualenvs/coreml-tools-o0SO9CVM-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/Users/michelschumacher/Library/Caches/pypoetry/virtualenvs/coreml-tools-o0SO9CVM-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5/models/common.py'>`

I know somebody received the same error and opened up an issue in another repo, but I think it could be helpfull for others if we try to solved it here.

**Comment by pytholic** [comment]
> Can't get attribute 'SPPF' on <module 'models.common' from '/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5/models/common.py'>

Hi. I think this [issue](https://github.com/ultralytics/yolov5/issues/5175) and this [issue](https://github.com/ultralytics/yolov5/issues/5143) might be helpful for you?

Also what happens if you try it with yolov5_4.0? Because I remember poetry repo does not support versions higher than 4.0 maybe.

**Comment by pytholic** [comment]
Also, take a look at this [link](https://programmerah.com/solved-training-yolov5-error-attributeerror-can-get-attribute-sppf-on-module-43954/).

I don't have the same setup atm, so building and installing stuff from scratch will take a lot of time for me.

**Comment by pytholic** [comment]
> Hello @pytholic,
> 
> first of all thanks for your repo! I had a lot of trouble converting yolov5 into coreml and your repo helped a lot. I was able to convert a model which was trained by somebody else, but the model isn't performing as good as I which. So I need to train it myself.
> 
> So at first I wanted to test if I could easily export a custom trained model with version 6 (I think I read somewhere that u trained you model with version 6), so I tried to convert the model from poetry_yolov5/yolov5_6.0. Unfortunately I did get this error
> 
> `Traceback (most recent call last): File "<string>", line 1, in <module> File "/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5-coreml-tools/src/coreml_export/main.py", line 313, in main model = torch.load(opt.model_input_path, map_location=torch.device('cpu'))[ File "/Users/michelschumacher/Library/Caches/pypoetry/virtualenvs/coreml-tools-o0SO9CVM-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 594, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/Users/michelschumacher/Library/Caches/pypoetry/virtualenvs/coreml-tools-o0SO9CVM-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load result = unpickler.load() AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5/models/common.py'>`
> 
> I know somebody received the same error and opened up an issue in another repo, but I think it could be helpfull for others if we try to solved it here.

Also, take a look at this [link](https://programmerah.com/solved-training-yolov5-error-attributeerror-can-get-attribute-sppf-on-module-43954/).

I don't have the same setup atm, so building and installing stuff from scratch will take a lot of time for me.

**Comment by pytholic** [comment]
> Hello @pytholic,
> 
> first of all thanks for your repo! I had a lot of trouble converting yolov5 into coreml and your repo helped a lot. I was able to convert a model which was trained by somebody else, but the model isn't performing as good as I which. So I need to train it myself.
> 
> So at first I wanted to test if I could easily export a custom trained model with version 6 (I think I read somewhere that u trained you model with version 6), so I tried to convert the model from poetry_yolov5/yolov5_6.0. Unfortunately I did get this error
> 
> `Traceback (most recent call last): File "<string>", line 1, in <module> File "/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5-coreml-tools/src/coreml_export/main.py", line 313, in main model = torch.load(opt.model_input_path, map_location=torch.device('cpu'))[ File "/Users/michelschumacher/Library/Caches/pypoetry/virtualenvs/coreml-tools-o0SO9CVM-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 594, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "/Users/michelschumacher/Library/Caches/pypoetry/virtualenvs/coreml-tools-o0SO9CVM-py3.8/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load result = unpickler.load() AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from '/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5/models/common.py'>`
> 
> I know somebody received the same error and opened up an issue in another repo, but I think it could be helpfull for others if we try to solved it here.

What I did was using model from v6.0, but source code from v4.0.

Also, I just compared `common.py` from yolov5_6.0 and yolov5_4.0. In 4.0, we do not have the `SPPF class` while in 6.0 we do. I think you should try using source code of yolov5_4.0 during conversion and it might work!

**Comment by MarleyRobert** [comment]
> > Can't get attribute 'SPPF' on <module 'models.common' from '/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5/models/common.py'>
> 
> Hi. I think this [issue](https://github.com/ultralytics/yolov5/issues/5175) and this [issue](https://github.com/ultralytics/yolov5/issues/5143) might be helpful for you?
> 
> Also what happens if you try it with yolov5_4.0? Because I remember poetry repo does not support versions higher than 4.0 maybe.

Hello @pytholic, thx for the reply! I tried converting the yolov5_4.0 and it worked fine. I will check the links later tonight or tomorrow.

> What I did was using model from v6.0, but source code from v4.0.
> 
> Also, I just compared `common.py` from yolov5_6.0 and yolov5_4.0. In 4.0, we do not have the `SPPF class` while in 6.0 we do. I think you should try using source code of yolov5_4.0 during conversion and it might work!

I already checked the common.py file and even tried to put the SPPF class in the common.py file from v4, but I did get another error. What exactly do you mean by 'using the model from v6, but source code from v4.0'? How can I merge them?

**Comment by pytholic** [comment]
> > > Can't get attribute 'SPPF' on <module 'models.common' from '/Users/michelschumacher/Yolov5Export-main/poetry_yolov5/yolov5/models/common.py'>
> > 
> > 
> > Hi. I think this [issue](https://github.com/ultralytics/yolov5/issues/5175) and this [issue](https://github.com/ultralytics/yolov5/issues/5143) might be helpful for you?
> > Also what happens if you try it with yolov5_4.0? Because I remember poetry repo does not support versions higher than 4.0 maybe.
> 
> Hello @pytholic, thx for the reply! I tried converting the yolov5_4.0 and it worked fine. I will check the links later tonight or tomorrow.
> 
> > What I did was using model from v6.0, but source code from v4.0.
> > Also, I just compared `common.py` from yolov5_6.0 and yolov5_4.0. In 4.0, we do not have the `SPPF class` while in 6.0 we do. I think you should try using source code of yolov5_4.0 during conversion and it might work!
> 
> I already checked the common.py file and even tried to put the SPPF class in the common.py file from v4, but I did get another error. What exactly do you mean by 'using the model from v6, but source code from v4.0'? How can I merge them?

So basically there are three things required here during conversion.
1. Our trained model (version 6)
2. Poetry repo (with all scripts etc.)
3. Source code of Yolo repo (basically clone of there repo)

When I say source code from version 4.0, I mean clone version 4.0 instead of 6.0. So your model is from version 6.0 but the source code you use during conversion will be of version 4.0.

Why source code from version 4.0? Because poetry repo supports only up to version 4.0. Higher version gave me some dimension mismatch error.
